CREATE DATABASE IF NOT EXISTS cyberfusion_soc DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE cyberfusion_soc;

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) NOT NULL,
  email VARCHAR(128) NULL,
  mobile VARCHAR(32) NULL,
  dept_id BIGINT NULL,
  post_id BIGINT NULL,
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1 enabled, 0 disabled',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_user_username (username),
  KEY idx_sys_user_status (status),
  KEY idx_sys_user_dept_id (dept_id),
  KEY idx_sys_user_post_id (post_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_dept (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  parent_id BIGINT NOT NULL DEFAULT 0,
  dept_name VARCHAR(64) NOT NULL,
  dept_code VARCHAR(64) NOT NULL,
  leader VARCHAR(64) NULL,
  phone VARCHAR(32) NULL,
  sort INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_dept_code (dept_code),
  KEY idx_sys_dept_parent_sort (parent_id, sort),
  KEY idx_sys_dept_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_post (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  post_code VARCHAR(64) NOT NULL,
  post_name VARCHAR(64) NOT NULL,
  sort INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_post_code (post_code),
  KEY idx_sys_post_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_code VARCHAR(64) NOT NULL,
  role_name VARCHAR(64) NOT NULL,
  data_scope VARCHAR(32) NOT NULL DEFAULT 'self' COMMENT 'self,dept,dept_tree,all,custom',
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_role_code (role_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_user_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_user_role (user_id, role_id),
  KEY idx_sys_user_role_role_id (role_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_menu (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  parent_id BIGINT NOT NULL DEFAULT 0,
  name VARCHAR(64) NOT NULL,
  path VARCHAR(128) NULL,
  component VARCHAR(128) NULL,
  icon VARCHAR(64) NULL,
  type VARCHAR(16) NOT NULL COMMENT 'directory, menu, button',
  permission VARCHAR(128) NULL,
  sort INT NOT NULL DEFAULT 0,
  visible TINYINT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_sys_menu_parent_sort (parent_id, sort),
  KEY idx_sys_menu_permission (permission),
  KEY idx_sys_menu_type (type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_role_menu (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_role_menu (role_id, menu_id),
  KEY idx_sys_role_menu_menu_id (menu_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_role_dept (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  role_id BIGINT NOT NULL,
  dept_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_role_dept (role_id, dept_id),
  KEY idx_sys_role_dept_dept_id (dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_dict_type (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  dict_name VARCHAR(64) NOT NULL,
  dict_code VARCHAR(64) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_dict_type_code (dict_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_dict_data (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  dict_type_id BIGINT NOT NULL,
  dict_label VARCHAR(64) NOT NULL,
  dict_value VARCHAR(64) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_sys_dict_data_type_sort (dict_type_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  config_key VARCHAR(128) NOT NULL,
  config_name VARCHAR(128) NOT NULL,
  config_value VARCHAR(1000) NOT NULL,
  value_type VARCHAR(32) NOT NULL DEFAULT 'string' COMMENT 'string, number, boolean, json',
  group_code VARCHAR(64) NOT NULL DEFAULT 'system',
  editable TINYINT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_config_key (config_key),
  KEY idx_sys_config_group (group_code),
  KEY idx_sys_config_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_notice (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  notice_title VARCHAR(128) NOT NULL,
  notice_type VARCHAR(32) NOT NULL,
  notice_content VARCHAR(4000) NOT NULL,
  pinned TINYINT NOT NULL DEFAULT 0,
  publish_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expire_at DATETIME NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_sys_notice_type (notice_type),
  KEY idx_sys_notice_status_time (status, publish_at, expire_at),
  KEY idx_sys_notice_pinned (pinned)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_login_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  ip VARCHAR(64) NULL,
  user_agent VARCHAR(500) NULL,
  status VARCHAR(32) NOT NULL,
  message VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_sys_login_log_created_at (created_at),
  KEY idx_sys_login_log_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_operation_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NULL,
  action VARCHAR(64) NOT NULL,
  method VARCHAR(16) NOT NULL,
  path VARCHAR(255) NOT NULL,
  ip VARCHAR(64) NULL,
  user_agent VARCHAR(500) NULL,
  status VARCHAR(32) NOT NULL,
  message VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_sys_operation_log_created_at (created_at),
  KEY idx_sys_operation_log_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_refresh_token (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  token_hash VARCHAR(128) NOT NULL,
  expires_at DATETIME NOT NULL,
  revoked TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sys_refresh_token_hash (token_hash),
  KEY idx_sys_refresh_token_user (user_id),
  KEY idx_sys_refresh_token_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_file (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  original_name VARCHAR(255) NOT NULL,
  stored_name VARCHAR(255) NOT NULL,
  file_ext VARCHAR(32) NOT NULL,
  content_type VARCHAR(128) NULL,
  file_size BIGINT NOT NULL,
  storage_type VARCHAR(32) NOT NULL DEFAULT 'local',
  storage_path VARCHAR(500) NOT NULL,
  access_url VARCHAR(500) NULL,
  md5 VARCHAR(64) NULL,
  biz_type VARCHAR(64) NULL,
  uploader_id BIGINT NULL,
  uploader_name VARCHAR(64) NULL,
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sys_file_biz_type (biz_type),
  KEY idx_sys_file_uploader_id (uploader_id),
  KEY idx_sys_file_md5 (md5),
  KEY idx_sys_file_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_attachment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  biz_type VARCHAR(64) NOT NULL,
  biz_id VARCHAR(64) NOT NULL,
  file_id BIGINT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_sys_attachment_biz (biz_type, biz_id),
  KEY idx_sys_attachment_file_id (file_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_import_export_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_no VARCHAR(64) NOT NULL,
  task_type VARCHAR(32) NOT NULL COMMENT 'IMPORT or EXPORT',
  template_code VARCHAR(128) NOT NULL,
  file_id BIGINT NULL,
  total_count INT NOT NULL DEFAULT 0,
  success_count INT NOT NULL DEFAULT 0,
  fail_count INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  error_summary VARCHAR(1000) NULL,
  operator_id BIGINT NULL,
  operator_name VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_import_export_log_task_no (task_no),
  KEY idx_sys_import_export_log_template_code (template_code),
  KEY idx_sys_import_export_log_status (status),
  KEY idx_sys_import_export_log_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_biz_sequence (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  sequence_code VARCHAR(64) NOT NULL,
  sequence_name VARCHAR(128) NOT NULL,
  prefix VARCHAR(32) NOT NULL DEFAULT '',
  date_pattern VARCHAR(32) NOT NULL DEFAULT 'yyyyMMdd',
  current_value BIGINT NOT NULL DEFAULT 0,
  step INT NOT NULL DEFAULT 1,
  length INT NOT NULL DEFAULT 4,
  reset_policy VARCHAR(32) NOT NULL DEFAULT 'DAILY',
  last_reset_date DATE NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_sys_biz_sequence_code (sequence_code),
  KEY idx_sys_biz_sequence_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS sys_biz_flow_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  biz_type VARCHAR(64) NOT NULL,
  biz_id VARCHAR(64) NOT NULL,
  biz_no VARCHAR(64) NULL,
  from_status VARCHAR(64) NULL,
  to_status VARCHAR(64) NULL,
  action VARCHAR(64) NOT NULL,
  operator_id BIGINT NULL,
  operator_name VARCHAR(64) NULL,
  reason VARCHAR(255) NULL,
  remark VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_sys_biz_flow_log_biz (biz_type, biz_id),
  KEY idx_sys_biz_flow_log_biz_no (biz_no),
  KEY idx_sys_biz_flow_log_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_alert (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  alert_uid VARCHAR(128) NOT NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'mock',
  level INT NOT NULL DEFAULT 0,
  severity VARCHAR(32) NOT NULL,
  rule_id VARCHAR(64) NOT NULL,
  rule_description VARCHAR(500) NOT NULL,
  asset_name VARCHAR(128) NOT NULL,
  asset_ip VARCHAR(64) NOT NULL,
  source_ip VARCHAR(64) NULL,
  event_type VARCHAR(64) NULL,
  target_url VARCHAR(500) NULL,
  action VARCHAR(64) NULL,
  evidence_summary VARCHAR(1000) NULL,
  batch_id VARCHAR(128) NULL,
  demo_case_id VARCHAR(128) NULL,
  correlation_key VARCHAR(255) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'new',
  tactic VARCHAR(128) NULL,
  raw_ref VARCHAR(255) NULL,
  event_time DATETIME NOT NULL,
  ticket_id BIGINT NULL,
  owner_id BIGINT NULL,
  dept_id BIGINT NULL,
  acknowledged_at DATETIME NULL,
  closed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_alert_uid (alert_uid),
  KEY idx_soc_alert_event_time (event_time),
  KEY idx_soc_alert_severity_status (severity, status),
  KEY idx_soc_alert_asset_ip (asset_ip),
  KEY idx_soc_alert_correlation (correlation_key),
  KEY idx_soc_alert_batch_demo (batch_id, demo_case_id),
  KEY idx_soc_alert_owner_dept (owner_id, dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_asset (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  hostname VARCHAR(128) NOT NULL,
  ip VARCHAR(64) NOT NULL,
  os_type VARCHAR(64) NOT NULL,
  risk_score INT NOT NULL DEFAULT 0,
  risk_level VARCHAR(32) NOT NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'mock',
  dept_id BIGINT NULL,
  dept_name VARCHAR(64) NULL,
  owner_id BIGINT NULL,
  owner_name VARCHAR(64) NULL,
  open_alert_count INT NOT NULL DEFAULT 0,
  last_seen_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_asset_ip (ip),
  KEY idx_soc_asset_risk (risk_level, risk_score),
  KEY idx_soc_asset_dept_owner (dept_id, owner_id),
  KEY idx_soc_asset_last_seen (last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_local_check_command (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  command_key VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  os_type VARCHAR(32) NOT NULL COMMENT 'Linux, macOS, Windows',
  category VARCHAR(64) NOT NULL COMMENT 'identity, network, process, startup, host, custom_readonly',
  description VARCHAR(500) NULL,
  command_argv_json JSON NOT NULL,
  timeout_seconds INT NOT NULL DEFAULT 2,
  output_limit_kb INT NOT NULL DEFAULT 8,
  enabled TINYINT NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT 'draft, active, disabled',
  version INT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 100,
  safety_note VARCHAR(500) NULL,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  approved_by BIGINT NULL,
  approved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_local_check_command_key_os (command_key, os_type, deleted),
  KEY idx_soc_local_check_command_os_status (os_type, status, enabled),
  KEY idx_soc_local_check_command_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_event_adapter_profile (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  source_type VARCHAR(32) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  description VARCHAR(500) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT 'draft, active, disabled',
  enabled TINYINT NOT NULL DEFAULT 1,
  version INT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 100,
  sample_file VARCHAR(255) NULL,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  approved_by BIGINT NULL,
  approved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_event_adapter_profile_source (source_type, deleted),
  KEY idx_soc_event_adapter_profile_status (status, enabled),
  KEY idx_soc_event_adapter_profile_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_event_field_mapping (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  adapter_id BIGINT NOT NULL,
  source_field_path VARCHAR(160) NOT NULL,
  normalized_field VARCHAR(80) NOT NULL,
  required TINYINT NOT NULL DEFAULT 0,
  transform_type VARCHAR(32) NOT NULL DEFAULT 'direct',
  default_value VARCHAR(255) NULL,
  example_value VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 100,
  enabled TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_soc_event_field_mapping_adapter (adapter_id, enabled, sort_order),
  KEY idx_soc_event_field_mapping_normalized (normalized_field)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_event_severity_mapping (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  adapter_id BIGINT NOT NULL,
  source_value VARCHAR(80) NOT NULL,
  normalized_severity VARCHAR(32) NOT NULL,
  risk_score INT NOT NULL DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_soc_event_severity_mapping_adapter (adapter_id, enabled),
  KEY idx_soc_event_severity_mapping_source (source_value)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_event_alert_link_rule (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  adapter_id BIGINT NOT NULL,
  event_type VARCHAR(80) NOT NULL DEFAULT '*',
  min_severity VARCHAR(32) NOT NULL DEFAULT 'medium',
  link_alerts_default TINYINT NOT NULL DEFAULT 1,
  alert_rule_id_field VARCHAR(80) NULL,
  alert_name_template VARCHAR(255) NULL,
  dedup_key_fields_json JSON NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_soc_event_alert_link_rule_adapter (adapter_id, enabled),
  KEY idx_soc_event_alert_link_rule_event_type (event_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_ticket (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  ticket_no VARCHAR(64) NOT NULL,
  alert_id BIGINT NULL,
  title VARCHAR(255) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  assignee_id BIGINT NULL,
  assignee_name VARCHAR(64) NULL,
  reviewer_id BIGINT NULL,
  review_conclusion VARCHAR(500) NULL,
  resolution VARCHAR(1000) NULL,
  dept_id BIGINT NULL,
  due_at DATETIME NULL,
  closed_at DATETIME NULL,
  archived_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_ticket_no (ticket_no),
  KEY idx_soc_ticket_alert_id (alert_id),
  KEY idx_soc_ticket_status (status),
  KEY idx_soc_ticket_assignee (assignee_id),
  KEY idx_soc_ticket_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_ticket_timeline (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  ticket_id BIGINT NOT NULL,
  action VARCHAR(64) NOT NULL,
  from_status VARCHAR(32) NULL,
  to_status VARCHAR(32) NULL,
  operator_name VARCHAR(64) NULL,
  remark VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_soc_ticket_timeline_ticket (ticket_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_response_playbook (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  playbook_key VARCHAR(80) NOT NULL,
  playbook_name VARCHAR(128) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  event_type VARCHAR(128) NULL,
  rule_id_pattern VARCHAR(255) NULL,
  min_severity VARCHAR(32) NOT NULL DEFAULT 'low',
  match_expression VARCHAR(500) NULL COMMENT '只允许说明性匹配描述，不支持脚本或表达式执行',
  description VARCHAR(500) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT 'draft, active, disabled',
  enabled TINYINT NOT NULL DEFAULT 1,
  version INT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 100,
  safety_note VARCHAR(500) NULL,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  approved_by BIGINT NULL,
  approved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_response_playbook_key (playbook_key, deleted),
  KEY idx_soc_response_playbook_match (source_type, status, enabled),
  KEY idx_soc_response_playbook_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_response_playbook_step (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  playbook_id BIGINT NOT NULL,
  step_key VARCHAR(80) NOT NULL,
  step_name VARCHAR(128) NOT NULL,
  step_type VARCHAR(64) NOT NULL COMMENT 'triage, contain, verify, remediate_manual, employee_confirm, report',
  owner_role VARCHAR(64) NOT NULL DEFAULT 'analyst',
  instruction VARCHAR(1000) NOT NULL,
  expected_evidence VARCHAR(1000) NULL,
  requires_employee TINYINT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 100,
  enabled TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_playbook_step_key (playbook_id, step_key, deleted),
  KEY idx_soc_playbook_step_playbook (playbook_id, enabled, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_ticket_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  ticket_id BIGINT NOT NULL,
  alert_id BIGINT NULL,
  playbook_id BIGINT NULL,
  playbook_step_id BIGINT NULL,
  task_key VARCHAR(160) NOT NULL,
  task_name VARCHAR(128) NOT NULL,
  task_type VARCHAR(64) NOT NULL,
  assignee_type VARCHAR(32) NOT NULL DEFAULT 'analyst' COMMENT 'analyst, employee',
  assignee_id BIGINT NULL,
  assignee_name VARCHAR(64) NULL,
  instruction VARCHAR(1000) NOT NULL,
  expected_evidence VARCHAR(1000) NULL,
  evidence_text VARCHAR(1000) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending, in_progress, submitted, confirmed, completed, skipped',
  sort_order INT NOT NULL DEFAULT 100,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  skipped_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_ticket_task_step (ticket_id, playbook_step_id, deleted),
  KEY idx_soc_ticket_task_ticket (ticket_id, status, sort_order),
  KEY idx_soc_ticket_task_assignee (assignee_type, assignee_id, status),
  KEY idx_soc_ticket_task_alert (alert_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_playbook_match_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  alert_id BIGINT NOT NULL,
  playbook_id BIGINT NOT NULL,
  ticket_id BIGINT NULL,
  match_reason VARCHAR(1000) NOT NULL,
  apply_status VARCHAR(32) NOT NULL DEFAULT 'suggested',
  operator_id BIGINT NULL,
  operator_name VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_soc_playbook_match_alert (alert_id, created_at),
  KEY idx_soc_playbook_match_playbook (playbook_id, apply_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_risk_scoring_policy (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  policy_code VARCHAR(80) NOT NULL,
  policy_name VARCHAR(128) NOT NULL,
  description VARCHAR(500) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT 'draft, active, disabled',
  enabled TINYINT NOT NULL DEFAULT 1,
  version INT NOT NULL DEFAULT 1,
  critical_asset_weight INT NOT NULL DEFAULT 10,
  internet_exposed_weight INT NOT NULL DEFAULT 10,
  critical_alert_weight INT NOT NULL DEFAULT 25,
  high_alert_weight INT NOT NULL DEFAULT 15,
  medium_alert_weight INT NOT NULL DEFAULT 8,
  critical_vulnerability_weight INT NOT NULL DEFAULT 25,
  high_vulnerability_weight INT NOT NULL DEFAULT 15,
  baseline_failed_weight INT NOT NULL DEFAULT 8,
  fim_unreviewed_weight INT NOT NULL DEFAULT 6,
  external_event_weight INT NOT NULL DEFAULT 6,
  incident_open_weight INT NOT NULL DEFAULT 12,
  incident_high_weight INT NOT NULL DEFAULT 20,
  overdue_ticket_weight INT NOT NULL DEFAULT 10,
  open_playbook_task_weight INT NOT NULL DEFAULT 6,
  employee_pending_task_weight INT NOT NULL DEFAULT 8,
  client_checkup_warning_weight INT NOT NULL DEFAULT 8,
  client_checkup_critical_weight INT NOT NULL DEFAULT 16,
  closed_ticket_reduce_weight INT NOT NULL DEFAULT 8,
  completed_playbook_reduce_weight INT NOT NULL DEFAULT 5,
  max_score INT NOT NULL DEFAULT 100,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  approved_by BIGINT NULL,
  approved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_risk_scoring_policy_code (policy_code, deleted),
  KEY idx_soc_risk_scoring_policy_status (status, enabled),
  KEY idx_soc_risk_scoring_policy_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_asset_risk_snapshot (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  asset_id BIGINT NOT NULL,
  asset_ip VARCHAR(64) NOT NULL,
  hostname VARCHAR(128) NOT NULL,
  score INT NOT NULL,
  risk_level VARCHAR(32) NOT NULL,
  policy_id BIGINT NULL,
  calculated_at DATETIME NOT NULL,
  factor_summary_json JSON NOT NULL,
  recommendation_summary VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_soc_asset_risk_snapshot_asset (asset_id, calculated_at),
  KEY idx_soc_asset_risk_snapshot_ip (asset_ip, calculated_at),
  KEY idx_soc_asset_risk_snapshot_score (score, risk_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_asset_risk_factor (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  snapshot_id BIGINT NOT NULL,
  asset_id BIGINT NOT NULL,
  factor_type VARCHAR(64) NOT NULL,
  factor_name VARCHAR(128) NOT NULL,
  factor_score INT NOT NULL DEFAULT 0,
  factor_count INT NOT NULL DEFAULT 0,
  related_biz_type VARCHAR(64) NULL,
  related_biz_id BIGINT NULL,
  explanation VARCHAR(1000) NOT NULL,
  recommendation VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_soc_asset_risk_factor_snapshot (snapshot_id),
  KEY idx_soc_asset_risk_factor_asset (asset_id, factor_type),
  KEY idx_soc_asset_risk_factor_related (related_biz_type, related_biz_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_client_checkup (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  checkup_no VARCHAR(64) NOT NULL,
  asset_id BIGINT NOT NULL,
  asset_ip VARCHAR(64) NOT NULL,
  asset_name VARCHAR(128) NOT NULL,
  os_type VARCHAR(64) NULL,
  score INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL COMMENT 'safe, attention, serious',
  summary VARCHAR(1000) NOT NULL,
  recommendation_summary VARCHAR(1000) NULL,
  owner_id BIGINT NULL,
  dept_id BIGINT NULL,
  operator_name VARCHAR(64) NULL,
  checked_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_client_checkup_no (checkup_no),
  KEY idx_soc_client_checkup_asset (asset_id, checked_at),
  KEY idx_soc_client_checkup_ip (asset_ip, checked_at),
  KEY idx_soc_client_checkup_scope (owner_id, dept_id),
  KEY idx_soc_client_checkup_status (status, score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_client_checkup_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  checkup_id BIGINT NOT NULL,
  item_type VARCHAR(64) NOT NULL,
  item_name VARCHAR(128) NOT NULL,
  severity VARCHAR(32) NOT NULL DEFAULT 'info',
  item_count INT NOT NULL DEFAULT 0,
  summary VARCHAR(1000) NOT NULL,
  recommendation VARCHAR(1000) NULL,
  sort_order INT NOT NULL DEFAULT 100,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_soc_client_checkup_item_checkup (checkup_id, sort_order),
  KEY idx_soc_client_checkup_item_type (item_type, severity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_client_recommendation_action (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  recommendation_key VARCHAR(96) NOT NULL,
  action_type VARCHAR(32) NOT NULL COMMENT 'note, confirm',
  note VARCHAR(500) NULL,
  related_type VARCHAR(32) NOT NULL COMMENT 'task, alert, vulnerability',
  related_id BIGINT NOT NULL,
  asset_ip VARCHAR(64) NOT NULL,
  asset_name VARCHAR(128) NULL,
  owner_id BIGINT NULL,
  dept_id BIGINT NULL,
  operator_name VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_soc_client_recommendation_key (recommendation_key, created_at),
  KEY idx_soc_client_recommendation_asset (asset_ip, created_at),
  KEY idx_soc_client_recommendation_scope (owner_id, dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_report (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  report_no VARCHAR(64) NOT NULL,
  report_type VARCHAR(32) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  summary VARCHAR(1000) NOT NULL,
  recommendation VARCHAR(1000) NOT NULL,
  generated_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_report_no (report_no),
  KEY idx_soc_report_period (report_type, period_start, period_end),
  KEY idx_soc_report_generated_at (generated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_wazuh_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  config_name VARCHAR(128) NOT NULL,
  manager_url VARCHAR(255) NULL,
  indexer_url VARCHAR(255) NULL,
  dashboard_url VARCHAR(255) NULL,
  auth_mode VARCHAR(32) NOT NULL DEFAULT 'env',
  enabled TINYINT NOT NULL DEFAULT 1,
  last_checked_at DATETIME NULL,
  last_status VARCHAR(64) NULL,
  remark VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_soc_wazuh_config_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_sync_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_code VARCHAR(64) NOT NULL,
  task_name VARCHAR(128) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  schedule_cron VARCHAR(64) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  last_status VARCHAR(64) NULL,
  last_run_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_sync_task_code (task_code),
  KEY idx_soc_sync_task_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_notification_channel (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  channel_name VARCHAR(128) NOT NULL,
  channel_type VARCHAR(32) NOT NULL,
  target VARCHAR(255) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  min_severity VARCHAR(32) NOT NULL DEFAULT 'medium',
  trigger_event VARCHAR(64) NOT NULL DEFAULT '*',
  send_mode VARCHAR(32) NOT NULL DEFAULT 'dry_run',
  last_status VARCHAR(64) NULL,
  last_sent_at DATETIME NULL,
  remark VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_soc_notification_channel_enabled (enabled),
  KEY idx_soc_notification_channel_type_event (channel_type, trigger_event)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_notification_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  channel_id BIGINT NULL,
  channel_type VARCHAR(32) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  severity VARCHAR(32) NULL,
  biz_type VARCHAR(64) NOT NULL,
  biz_id BIGINT NULL,
  title VARCHAR(255) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  target VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  error_message VARCHAR(500) NULL,
  sent_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_soc_notification_log_event (event_type, created_at),
  KEY idx_soc_notification_log_biz (biz_type, biz_id),
  KEY idx_soc_notification_log_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_alert_whitelist (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  rule_name VARCHAR(128) NOT NULL,
  rule_id VARCHAR(64) NULL,
  asset_ip VARCHAR(64) NULL,
  source_ip VARCHAR(64) NULL,
  severity VARCHAR(32) NULL,
  reason VARCHAR(500) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  match_count INT NOT NULL DEFAULT 0,
  last_matched_at DATETIME NULL,
  owner_id BIGINT NULL,
  dept_id BIGINT NULL,
  expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  KEY idx_soc_alert_whitelist_enabled (enabled),
  KEY idx_soc_alert_whitelist_rule_asset (rule_id, asset_ip),
  KEY idx_soc_alert_whitelist_scope (owner_id, dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_external_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_uid VARCHAR(128) NOT NULL,
  source_type VARCHAR(32) NOT NULL COMMENT 'wazuh, zeek, suricata, trivy, misp, zap, sigma, shuffle and optional sources',
  event_type VARCHAR(64) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  rule_id VARCHAR(64) NULL,
  rule_name VARCHAR(255) NULL,
  src_ip VARCHAR(64) NULL,
  dest_ip VARCHAR(64) NULL,
  asset_name VARCHAR(128) NULL,
  asset_ip VARCHAR(64) NULL,
  batch_id VARCHAR(128) NULL,
  demo_case_id VARCHAR(128) NULL,
  target_url VARCHAR(500) NULL,
  action VARCHAR(64) NULL,
  request_id VARCHAR(128) NULL,
  correlation_key VARCHAR(255) NULL,
  ioc VARCHAR(255) NULL,
  raw_event JSON NULL,
  normalized_event JSON NULL,
  alert_id BIGINT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'new',
  owner_id BIGINT NULL,
  dept_id BIGINT NULL,
  event_time DATETIME NOT NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_external_event_uid (event_uid),
  KEY idx_soc_external_source_type (source_type, event_type),
  KEY idx_soc_external_severity_status (severity, status),
  KEY idx_soc_external_asset (asset_ip, dest_ip),
  KEY idx_soc_external_correlation (correlation_key),
  KEY idx_soc_external_batch_demo (batch_id, demo_case_id),
  KEY idx_soc_external_ioc (ioc),
  KEY idx_soc_external_alert (alert_id),
  KEY idx_soc_external_scope (owner_id, dept_id),
  KEY idx_soc_external_event_time (event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_correlation_rule (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  rule_code VARCHAR(128) NULL,
  rule_key VARCHAR(128) NOT NULL,
  rule_name VARCHAR(128) NOT NULL,
  description VARCHAR(500) NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  version INT NOT NULL DEFAULT 1,
  rule_type VARCHAR(64) NOT NULL COMMENT 'event_count, frequency, temporal, temporal_ordered, cross_source_chain',
  time_window_minutes INT NULL,
  min_score INT NULL,
  min_count INT NULL,
  group_by_fields_json JSON NULL,
  source_types_json JSON NULL,
  event_types_json JSON NULL,
  group_by_json JSON NULL,
  threshold INT NOT NULL DEFAULT 2,
  timeframe_seconds INT NOT NULL DEFAULT 1800,
  sequence_json JSON NULL,
  severity_min VARCHAR(32) NULL,
  severity_floor VARCHAR(32) NULL,
  weights_json JSON NULL,
  safety_note VARCHAR(500) NULL,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,
  approved_by BIGINT NULL,
  approved_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_correlation_rule_key (rule_key, deleted),
  KEY idx_soc_correlation_rule_status (status, enabled),
  KEY idx_soc_correlation_rule_type (rule_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_incident_cluster (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  cluster_no VARCHAR(128) NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary VARCHAR(1000) NULL,
  recommendation VARCHAR(1000) NULL,
  severity VARCHAR(32) NOT NULL DEFAULT 'medium',
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  score INT NOT NULL DEFAULT 0,
  correlation_key VARCHAR(255) NOT NULL,
  asset_id BIGINT NULL,
  asset_ip VARCHAR(64) NULL,
  hostname VARCHAR(128) NULL,
  primary_asset_ip VARCHAR(64) NULL,
  primary_hostname VARCHAR(128) NULL,
  batch_id VARCHAR(128) NULL,
  demo_case_id VARCHAR(128) NULL,
  source_summary VARCHAR(255) NULL,
  source_types VARCHAR(255) NULL,
  evidence_count INT NOT NULL DEFAULT 0,
  event_count INT NOT NULL DEFAULT 0,
  alert_count INT NOT NULL DEFAULT 0,
  vulnerability_count INT NOT NULL DEFAULT 0,
  first_seen_at DATETIME NULL,
  last_seen_at DATETIME NULL,
  rule_id BIGINT NULL,
  rule_key VARCHAR(128) NULL,
  ticket_id BIGINT NULL,
  owner_id BIGINT NULL,
  dept_id BIGINT NULL,
  closed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_incident_cluster_no (cluster_no),
  UNIQUE KEY uk_soc_incident_correlation (correlation_key),
  KEY idx_soc_incident_status (status, severity),
  KEY idx_soc_incident_asset (primary_asset_ip),
  KEY idx_soc_incident_batch_demo (batch_id, demo_case_id),
  KEY idx_soc_incident_scope (owner_id, dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_incident_evidence (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  cluster_id BIGINT NOT NULL,
  evidence_type VARCHAR(32) NOT NULL COMMENT 'external_event, alert, vulnerability',
  evidence_id BIGINT NOT NULL,
  evidence_uid VARCHAR(128) NULL,
  source_type VARCHAR(32) NULL,
  event_type VARCHAR(64) NULL,
  severity VARCHAR(32) NULL,
  rule_id VARCHAR(128) NULL,
  asset_ip VARCHAR(64) NULL,
  hostname VARCHAR(128) NULL,
  target_url VARCHAR(500) NULL,
  batch_id VARCHAR(128) NULL,
  demo_case_id VARCHAR(128) NULL,
  event_time DATETIME NULL,
  relation_score INT NOT NULL DEFAULT 0,
  relation_reason VARCHAR(1000) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_incident_evidence (cluster_id, evidence_type, evidence_id),
  KEY idx_soc_incident_evidence_lookup (evidence_type, evidence_id),
  KEY idx_soc_incident_evidence_asset (asset_ip),
  KEY idx_soc_incident_evidence_batch_demo (batch_id, demo_case_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_algorithm_evaluation (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  evaluation_no VARCHAR(64) NOT NULL,
  algorithm_type VARCHAR(64) NOT NULL COMMENT 'all, correlation, risk_scoring, recommendation, trend_anomaly',
  policy_id BIGINT NULL,
  policy_version INT NULL,
  batch_id VARCHAR(128) NULL,
  time_range_start DATETIME NULL,
  time_range_end DATETIME NULL,
  input_count INT NOT NULL DEFAULT 0,
  output_count INT NOT NULL DEFAULT 0,
  diff_summary_json JSON NULL,
  result_summary VARCHAR(1000) NOT NULL,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_soc_algorithm_evaluation_no (evaluation_no),
  KEY idx_soc_algorithm_evaluation_type (algorithm_type, created_at),
  KEY idx_soc_algorithm_evaluation_batch (batch_id, created_at),
  KEY idx_soc_algorithm_evaluation_operator (created_by, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_algorithm_evaluation_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  evaluation_id BIGINT NOT NULL,
  item_type VARCHAR(64) NOT NULL COMMENT 'incident_cluster, risk_change, recommendation, trend_anomaly',
  item_name VARCHAR(255) NOT NULL,
  preview_result_json JSON NULL,
  reason VARCHAR(1000) NOT NULL,
  sort_order INT NOT NULL DEFAULT 100,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_soc_algorithm_eval_item_eval (evaluation_id, sort_order),
  KEY idx_soc_algorithm_eval_item_type (item_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_vulnerability (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  cve_id VARCHAR(64) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  asset_name VARCHAR(128) NOT NULL,
  asset_ip VARCHAR(64) NOT NULL,
  software_name VARCHAR(128) NOT NULL,
  software_version VARCHAR(128) NULL,
  fix_suggestion VARCHAR(1000) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  source_type VARCHAR(32) NOT NULL DEFAULT 'mock',
  owner_id BIGINT NULL,
  dept_id BIGINT NULL,
  detected_at DATETIME NOT NULL,
  fixed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_vuln_cve_asset (cve_id, asset_ip, software_name),
  KEY idx_soc_vuln_severity_status (severity, status),
  KEY idx_soc_vuln_asset (asset_ip),
  KEY idx_soc_vuln_owner_dept (owner_id, dept_id),
  KEY idx_soc_vuln_detected_at (detected_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_baseline_check (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  check_code VARCHAR(64) NOT NULL,
  category VARCHAR(64) NOT NULL,
  check_item VARCHAR(255) NOT NULL,
  asset_name VARCHAR(128) NOT NULL,
  asset_ip VARCHAR(64) NOT NULL,
  result VARCHAR(32) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  pass_rate INT NOT NULL DEFAULT 0,
  remediation VARCHAR(1000) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'failed',
  source_type VARCHAR(32) NOT NULL DEFAULT 'mock',
  owner_id BIGINT NULL,
  dept_id BIGINT NULL,
  checked_at DATETIME NOT NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_baseline_check_asset (check_code, asset_ip),
  KEY idx_soc_baseline_category_result (category, result),
  KEY idx_soc_baseline_status (status),
  KEY idx_soc_baseline_owner_dept (owner_id, dept_id),
  KEY idx_soc_baseline_checked_at (checked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS soc_file_integrity_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_uid VARCHAR(128) NOT NULL,
  action VARCHAR(32) NOT NULL,
  severity VARCHAR(32) NOT NULL,
  hostname VARCHAR(128) NOT NULL,
  asset_ip VARCHAR(64) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  rule_name VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'new',
  source_type VARCHAR(32) NOT NULL DEFAULT 'mock',
  owner_id BIGINT NULL,
  dept_id BIGINT NULL,
  event_time DATETIME NOT NULL,
  reviewed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_soc_fim_event_uid (event_uid),
  KEY idx_soc_fim_action_status (action, status),
  KEY idx_soc_fim_asset_path (asset_ip, file_path(128)),
  KEY idx_soc_fim_owner_dept (owner_id, dept_id),
  KEY idx_soc_fim_event_time (event_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
